In [3]:
import numpy as np


In [7]:
angulos_0_90 = np.array([0,30,45,60,90])
angulos_0_90

array([ 0, 30, 45, 60, 90])

In [9]:
#En numpy ya existe la variable pi <- universal function
radianes = angulos_0_90*np.pi/180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [11]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [12]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

1

In [9]:
#El numero de enteros positivos contando con el cero
arreglo_random = np.random.randint(10) # 10 enteros de 0-9
arreglo_random
arreglo_random1 = np.random.randint(15,35,5)
arreglo_random1

array([23, 30, 28, 19, 21])

In [101]:
arreglo_random = np.random.randint(-5,5) # numeros desde -5 a 4 ==[-5, 5[
arreglo_random

-1

In [110]:
arreglo_random = np.random.randint(
    -5,
    5,
    3 
) # 3 numeros en el intervalo [-5, 5[
arreglo_random

array([ 2, -2, -4])

In [123]:
#calculo de l media
np.mean(arreglo_random)

-1.3333333333333333

In [124]:
#calculo de la mediana
np.median(arreglo_random)

-2.0

In [125]:
#calculo de la desviacion estandar
np.std(arreglo_random)

2.494438257849294

In [126]:
#calculo de la varianza
np.var(arreglo_random)

6.222222222222221

-1.3333333333333333